# See options here = https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  windowSize: 'half' # requires lazygit 0.37.0
  showFileTree: false
  showRandomTip: false
  mainPanelSplitMode: 'horizontal'
  diffView:
    sideBySide: false
  expandFocusedSidePanel: true
  showFileTree: true
  border: 'rounded'
git:
  autoFetch: false
  fetchAll: false # only fetch current branch
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme base16-256
os:
  editPreset: 'nvim'
notARepository: 'quit'
quitOnTopLevelReturn: true

