#!/bin/zsh

# tmux display-message -d 2000 "#[align=centre]Loading projects..."

frecency="${0:h}/../bin/frecency"

# List of project roots, all are assumed to be below $HOME
project_roots=(${(s/:/)PROJECT_ROOTS})

# 1. Get all project folders without trailing slash
project_folders=($(fd --min-depth 1 --max-depth 1 -t directory . ${project_roots[@]} | xargs realpath))
project_folders+=($(fd --min-depth 1 --max-depth 1 -t symlink . ${project_roots[@]}))

# 1.1. Add any additional project folders we don't want to expand
project_folders+=(${(s/:/)PROJECT_FOLDERS})

# 2. Construct a list of home-relative project folders
selection_list=()
for folder in "${project_folders[@]}"; do
  # change to project folder (also filters out inaccessible folders)
  cd $folder || continue

  # shorten folder path
  local short_folder=$(echo $folder | sed "s|$HOME/||")
  selection_list+=("$short_folder")

  # return to previous folder
  cd - > /dev/null
done

# 3. Select a project using fzf, ranked by frecency (all paths relative to $HOME)
selected_item=$(printf '%s\n' "${selection_list[@]}" | $frecency projects rank | fzf-tmux --reverse -w 50% -h 50% --tiebreak=index)
local retval=$?
if (($retval == 0)); then
  # 3.1. Get the selected folder from the selected item
  selected_folder=$(echo $selected_item | awk '{print $1}')
  selected_path="$HOME/$selected_folder"
  # strip leading dot
  session_name=$(echo $selected_folder | sed 's|^\.*||')

  # 3.2. Record this pick for future frecency ranking
  $frecency projects add "$selected_folder"

	# 4. Switch to the workspace by communicating with wezterm
  tmux_running=$(pgrep tmux)

  if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $session_name -c $selected_path
    exit 0
  fi

  if ! tmux has-session -t=$session_name 2>/dev/null; then
    tmux new-session -ds $session_name -c $selected_path
  fi

  tmux switch-client -t $session_name
  exit 0
else
	# user cancelled fzf, but we don't want to show anything in tmux
  exit 0
fi
