#!/usr/bin/env bash

if [[ "$OS" == "mac" ]]; then
  if ! test -d /Applications/Firefox.app; then
    echo "Firefox is not installed. Installing Firefox..."
    brew install --cask firefox
  else
    echo "Firefox is already installed. Skipping installation."
    exit 0
  fi
else
  echo "Firefox installation not supported on this OS: $OS, $OS_BASE"
fi
